<a href="https://colab.research.google.com/github/19pa1a0450/VIJAY-PRAKASH/blob/master/vijay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=10
b=13
if(a>b):
  print(a,"is the largest number")
else:
  print(b,"is the largest number")
    

13 is the largest number


In [4]:
r=int(input("enter the positive range"))
for i in range (1,r+1):
  if (i%2==0):
    print(i,"is a even number")
  else:
    print(i,"is a odd number")  

  


enter the positive range10
1 is a odd number
2 is a even number
3 is a odd number
4 is a even number
5 is a odd number
6 is a even number
7 is a odd number
8 is a even number
9 is a odd number
10 is a even number


In [7]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
x=np.array([1,2,3,'n',4])
print(x)
print(type(x))

['1' '2' '3' 'n' '4']
<class 'numpy.ndarray'>


In [11]:
import numpy as np
y=np.linspace(start=1,stop=5)
print(y)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [12]:
import numpy as np
x=np.arange(start=1,stop=20,step=2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [14]:
import numpy as np
x=np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
import numpy as np
x=np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
import numpy as np
x=np.random.rand(2,5)
print(x)

[[0.23088905 0.62819668 0.87681881 0.66471877 0.90905792]
 [0.43786002 0.5040802  0.8090316  0.66722843 0.57489892]]


In [18]:
import numpy as np
x=np.random.rand(10)
x=x.astype(int)
print(x)

[0 0 0 0 0 0 0 0 0 0]
