<a href="https://colab.research.google.com/github/19pa1a0450/VIJAY-PRAKASH/blob/master/vijay1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
x=np.arange(start=1,stop=10).reshape(3,3)
print(x[1,1])



5


In [5]:
print(x[1:3])

[[4 5 6]
 [7 8 9]]


In [6]:
print(x[2:1])

[]


In [7]:
print(x[2:])

[[7 8 9]]
